const Status = Object.freeze({
  RECEIVED: "RECEIVED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  SENT_TO_CUSTOMS: "SENT_TO_CUSTOMS",
  CUSTOMS_SEND_FAILED: "CUSTOMS_SEND_FAILED",
  WAITING_VERIFICATION_CODE: "WAITING_VERIFICATION_CODE",
  VERIFICATION_REQUEST_SENT: "VERIFICATION_REQUEST_SENT",
  VERIFICATION_CODE_RECEIVED: "VERIFICATION_CODE_RECEIVED",
  SENT_TO_INTERNAL_SYSTEM: "SENT_TO_INTERNAL_SYSTEM",
  INTERNAL_SEND_FAILED: "INTERNAL_SEND_FAILED",
  COMPLETED: "COMPLETED"
});

const VerificationStatus = Object.freeze({
  NOT_REQUESTED: "NOT_REQUESTED",
  SENT: "SENT",
  RECEIVED: "RECEIVED",
  EXPIRED: "EXPIRED",
  NEEDS_RETRY: "NEEDS_RETRY"
});

module.exports = { Status, VerificationStatus };
